apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-ai-tools-message-broker.fullname" . }}
  labels:
    {{- include "secure-ai-tools-message-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: amqp
      protocol: TCP
      name: amqp
  selector:
    {{- include "secure-ai-tools-message-broker.selectorLabels" . | nindent 4 }}
