apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-ai-tools-db.fullname" . }}
  labels:
    {{- include "secure-ai-tools-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "secure-ai-tools-db.selectorLabels" . | nindent 4 }}
