apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-ai-tools-web.fullname" . }}
  labels:
    {{- include "secure-ai-tools-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "secure-ai-tools-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secure-ai-tools-web.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secure-ai-tools-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh', '-c']
          args: ["cd /app && node apps/web/server.js"]
          # args: ["sleep infinity"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          envFrom:
          - secretRef:
              # name: {{ include "secure-ai-tools-web.fullname" . }}-db-secret
              name: "{{ .Values.DBSecretName }}"
          - secretRef:
              # name: {{ include "secure-ai-tools-web.fullname" . }}-amqp-secret
              name: "{{ .Values.AMQPSecretName }}"
          - secretRef:
              name: "{{ .Values.random_pw_secret_name_next_auth }}"
          - secretRef:
              name: "{{ .Values.random_pw_secret_name_analytics }}"
          env:
          - name: INFERENCE_SERVER
            value: "http://{{ .Values.inferenceHost }}:{{ .Values.inferencePort }}"
          - name: VECTOR_DB_SERVER
            value: "http://{{ .Values.vectorDBHost }}:{{ .Values.vectorDBPort }}"
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: "{{ $val }}"
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
