---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.random_pw_secret_name_analytics }}"
  {{- if .Values.random_pw_secret_resource_policy_keep_analytics }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- end }}
type: Opaque
data:
{{- if .Values.secretDataAnalytics -}}
  {{- range $k, $v := .Values.secretDataAnalytics }}
    "{{ $k }}": "{{ tpl $v $ | b64enc }}"
  {{- end }}
{{- end -}}
