---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.random_pw_secret_name_next_auth }}"
  {{- if .Values.random_pw_secret_resource_policy_keep_next_auth }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- end }}
type: Opaque
data:
{{- if .Values.secretDataNextAuth -}}
  {{- range $k, $v := .Values.secretDataNextAuth }}
    "{{ $k }}": "{{ tpl $v $ | b64enc }}"
  {{- end }}
{{- end -}}
